hyp = {
    "task": "slimevolley",
    "maxGen": 8,
    "alg_nReps": 2,
    "alg_speciate": "neat",
    "alg_probMoo": 0.0,
    "alg_act": 5,
    "prob_addConn": 0.5,
    "prob_addNode": 0.3,
    "prob_crossover": 0.8,
    "prob_enable": 0.01,
    "prob_mutAct": 0.0,
    "prob_mutConn": 0.8,
    "prob_initEnable": 1.0,
    "select_cullRatio": 0.1,
    "select_eliteRatio": 0.1,
    "select_rankWeight": "exp",
    "select_tournSize": 2,
    "spec_compatMod": 0.25,
    "spec_dropOffAge": 64,
    "spec_target": 4,
    "spec_thresh": 2.0,
    "spec_threshMin": 2.0,
    "spec_geneCoef": 1,
    "spec_weightCoef": 0.5,
    "save_mod": 8,
    "bestReps": 20,
    "ann_nInput": 12,
    "ann_nOutput": 3,
    "ann_initAct": 0,
    "ann_absWCap": 2.0,
    "ann_mutSigma": 0.4,
    "ann_actRange": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    "popSize": 8,
}
